#!/usr/bin/tclsh

if {$argc != 4 && $argc != 5} {
    puts "Usage: $argv0 <filename> <outer-npt> <inner-npt> <knots> \[mesh\]"
    exit
}

set mesh [lassign $argv filename outer inner knots]
set prologue "./quadfit-test $filename"
set stats "--print-continuity-errors --print-approximation-errors"

if {$mesh ne ""} {
    lappend prologue --mesh=$mesh
    lappend stats --deviation-map
}

if {$outer eq "n" && $inner eq "n"} {
    set cmd "$prologue --cubic-fit=$knots --fix-c0-inside --fix-c0-outside $stats"
} elseif {$outer eq "t" && $inner eq "p"} {
    set cmd "$prologue --fit-curves --extra-knots=$knots --retain-boundaries --retain-ribbons $stats"
} elseif {$outer eq "t" && $inner eq "n"} {
    set cmd "$prologue --extra-knots=$knots --retain-ribbons $stats"
} else {
    puts "Error: configuration not implemented"
    exit
}

puts "Executing: $cmd"
puts [exec {*}$cmd]
